apiVersion: v1 
kind: Service 
metadata: 
  labels:
    app: nginx-app
    name: nginx
  name: sf-webserver
spec: 
  selector: 
    app: nginx-app
    name: nginx
  type: NodePort 
  ports:
  - name: nginx-port 
    port: 80
    protocol: TCP
    targetPort: nginx-port
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx-sf
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx-app
      name: nginx
  template:
    metadata:
      labels:
        app: nginx-app
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80 
          name: nginx-port
          protocol: TCP
        volumeMounts: 
          - name: nginx-conf-file 
            mountPath: /etc/nginx/nginx.conf 
            subPath: "nginx.conf" 
            readOnly: true
          - name: auth-basic
            mountPath: /etc/apache2/.htpasswd
            subPath: ".htpasswd"
            readOnly: true
      volumes: 
        - name: nginx-conf-file
          configMap:
            name: nginx-conf 
            items:
            - key: "nginx.conf"
              path: "nginx.conf"
        - name: auth-basic
          secret:
            secretName: auth-basic
